baseURL: https://mfbolus.github.io/eg-cpp-library
languageCode: en-us
title: Example C++ Library
theme: learn
pygmentsUseClasses: false
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsStyle: "tango"
